In [1]:
import numpy as np

In [2]:
np.zeros(3)

array([0., 0., 0.])

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
np.ones(3)

array([1., 1., 1.])

In [5]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [7]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# Memakai fungsi seed untuk menyamakan semua angka di random.rand(menyamakan dgn teman yg lain)
np.random.seed(101)

In [10]:
np.random.rand(2)

array([0.51639863, 0.57066759])

In [11]:
np.random.rand(5,5)

array([[0.02847423, 0.17152166, 0.68527698, 0.83389686, 0.30696622],
       [0.89361308, 0.72154386, 0.18993895, 0.55422759, 0.35213195],
       [0.1818924 , 0.78560176, 0.96548322, 0.23235366, 0.08356143],
       [0.60354842, 0.72899276, 0.27623883, 0.68530633, 0.51786747],
       [0.04848454, 0.13786924, 0.18696743, 0.9943179 , 0.5206654 ]])

In [12]:
np.random.randn(2)

array([1.58917569, 0.53322084])

In [13]:
np.random.randn(2)

array([0.85734924, 0.08707633])

In [14]:
np.random.seed()

In [15]:
np.random.randn(2)

array([-0.91869431,  1.06401558])

In [16]:
np.random.randn(5,5)

array([[-1.40877456, -1.57881403,  1.63629176,  1.54506037,  0.85654362],
       [ 0.89974611, -0.30022643, -1.07047051,  0.74925114,  0.48237013],
       [ 0.63951463, -0.06812899,  1.142916  , -0.6575714 , -0.58029105],
       [ 0.04085049, -0.86923624, -0.07213208, -0.37846027, -0.99516091],
       [ 0.36333144, -0.19162746, -0.48100934,  1.51605383,  1.91275646]])

In [17]:
np.random.randint(1,100)

75

In [18]:
np.random.randint(1,100)

65

In [19]:
np.random.randint(1,100,10)

array([93, 16, 14, 11, 85, 94, 92, 47, 79, 31])

In [20]:
# random.randint untuk hasil angka int
arr = np.arange(25)
ranaar = np.random.randint(0,50,10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
ranaar

array([16,  8, 11, 20,  5, 30, 37, 11, 18, 20])

In [22]:
np.random.randint(1,4)

3

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
ranaar

array([16,  8, 11, 20,  5, 30, 37, 11, 18, 20])

In [25]:
ranaar.max()

37

In [27]:
# melihat indeks terbesar
ranaar.argmax()

6

In [28]:
ranaar.min()

5

In [29]:
# melihat indeks terkecil
ranaar.argmin()

4

In [30]:
ranaar.mean()

17.6

In [31]:
ranaar.std()

9.393614852653903

In [32]:
# vector
arr.shape

(25,)