### ini Heading
ini utk menjelaskan apa itu cell

In [1]:
# Belajar numpy
import numpy as np

In [2]:
list_kosong = []


In [3]:
for i in range(4):
    list_kosong.append(i)

In [4]:
print(i)

3


In [5]:
print(list_kosong)

[0, 1, 2, 3]


In [6]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [7]:
np.array(my_list)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[8]

8

In [14]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
arr[[1,3]] = 100

In [17]:
arr

array([  0, 100,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [18]:
# arr = np.arange(0,11)
# arr

In [ ]:
# indexing row
arr_2d[1]

In [ ]:
# format is arr_2d(row)(col) or (row,col)
# getting individual element value
arr_2d[1][0]

In [ ]:
# getting individual element value
arr_2d[1,0]

In [ ]:
# 2d array is slicing
# shape (2,2) from top right corner
arr_2d[:2,1:]

# Fancy Indexing

In [20]:
# set up matrix
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
# length of array
arr_length = arr2d.shape[0]
arr_length

10

In [22]:
# set up array
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [23]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [24]:
# Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# Selection

In [25]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [27]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])